#!/bin/sh
MP3PATH=`./setting Mp3Path`
ALLALBUMSPATH=`./setting AllAlbumsPath`
UPDATEDB=updatedb

# FreeBSD support
if which gupdatedb; then
	UPDATEDB=gupdatedb
fi

case `${UPDATEDB} --version` in
	*findutils*)
		${UPDATEDB} --localpaths=${ALLALBUMSPATH} --output=${MP3PATH}mp3.db
		;;
	*mlocate*)
		${UPDATEDB} --database-root ${ALLALBUMSPATH} -o ${MP3PATH}mp3.db
		;;
esac

chmod 664 ${MP3PATH}mp3.db
