#!/bin/sh
cd `dirname \`dirname $0\``
LOGPATH=`tools/setting LogPath`

php taggers/albumtagger.php >> ${LOGPATH}
php taggers/playlisttagger.php >> ${LOGPATH}
php processors/recordprocessor.php >> ${LOGPATH}
php processors/albumprocessor.php >> ${LOGPATH}
php collectors/artistcollector.php >> ${LOGPATH}
php collectors/compilationcollector.php >> ${LOGPATH}
php collectors/soundtrackcollector.php >> ${LOGPATH}
php collectors/taggedcollector.php >> ${LOGPATH}
php collectors/fullalbumcollector.php >> ${LOGPATH}

tools/updatesearch

php test/checkrecords.php
php test/checkreleases.php
php test/checkalbums.php
