#!/bin/sh
cd `dirname \`dirname $0\``
MP3PATH=`./setting Mp3Path`
MP3OWNER=`./setting Mp3Owner`

chown -R ${MP3OWNER} ${MP3PATH}{All,Albums,Playlists,Queue,Untaggable}
chmod 777 -R ${MP3PATH}Queue/{Albums,Playlists}
